### ISSUE TITLE
www-apps/mattermost-server: where do you get COMMIT hashes?

### ISSUE THREAD

**Issue by lkraav** [matoro/overlay#2]
Hi. Thanks for continuing chaoslab work!

```sh
GIT_COMMIT="f5e67b709f469f3b7b06c0c1be13b78c17fd4dfb"
WEBAPP_COMMIT="35295d64e621f1c1999a34f53ecf76d8228f9629"
```

Where do these values comes from?

**Comment by lkraav** [comment]
Nevermind, I got the matching HEAD values for https://github.com/mattermost/mattermost-server/tree/v7.1.1 and https://github.com/mattermost/mattermost-webapp/tree/v7.1.1 was looking at the wrong version before.

**Comment by matoro** [comment]
Sorry this is super out-of-date too!  I don't run Mattermost in prod anymore so I haven't been as attentive in keeping it updated.  Feel free to open issues/PRs if it falls too far behind.

**Comment by lkraav** [comment]
> Sorry this is super out-of-date too! I don't run Mattermost in prod anymore so I haven't been as attentive in keeping it updated.

What did you switch to?

**Comment by matoro** [comment]
> > Sorry this is super out-of-date too! I don't run Mattermost in prod anymore so I haven't been as attentive in keeping it updated.
> 
> What did you switch to?

Nothing.  I already ran Synapse for personal comms and the Mattermost instance I administered for my team at work, but I left that job, so I transferred the database to a teammate and shut it down.  They still use it there, just not run by me anymore.
